# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, camera_index: 0, width: 640, height: 480}}" \
    --robot.id=black \
    --dataset.repo_id=aliberts/record-test \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so100_follower \
  --robot.left_arm_port=/dev/tty.usbmodem5A460851411 \
  --robot.right_arm_port=/dev/tty.usbmodem5A460812391 \
  --robot.id=bimanual_follower \
  --robot.cameras='{
    left: {"type": "opencv", "index_or_path": 0, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    right: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30}
  }' \
  --teleop.type=bi_so100_leader \
  --teleop.left_arm_port=/dev/tty.usbmodem5A460828611 \
  --teleop.right_arm_port=/dev/tty.usbmodem5A460826981 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so100-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

import logging
import os
import readline
import select
import sys
import termios
import threading
import time
from concurrent.futures import Future, ThreadPoolExecutor
from dataclasses import asdict, dataclass
from pathlib import Path
from pprint import pformat

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.utils import build_dataset_frame, hw_to_dataset_features
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_so100_follower,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    so100_follower,
    so101_follower,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_so100_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    so100_leader,
    so101_leader,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.robot_utils import busy_wait
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import _init_rerun, log_rerun_data


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


class BackgroundVideoEncoder:
    """
    将 PNG→MP4 编码移到单独的后台线程，让主线程在编码进行中就能立即开始录制下一集。

    设计要点
    --------
    * **单 worker**：``ThreadPoolExecutor(max_workers=1)`` 保证编码任务顺序执行，
      不会出现多任务并发争抢 CPU（SVT-AV1 内部已多线程）。
    * **episode 0 的写竞争**：``encode_episode_videos(0)`` 在编码结束后会调用
      ``meta.update_video_info() + write_info()``；而主线程在保存 episode 1 的元数据时
      也会调用 ``meta.save_episode() + write_info()``。
      两者会同时写 ``info.json``，造成数据丢失。
      解决方法：在保存任意 episode > 0 的数据之前调用 ``ensure_ep0_done()``，
      等待 episode 0 编码完成（实践中此调用几乎总是立即返回，
      因为 ep0 编码 ≈10-30 s，而录 ep1 需要 60 s+）。
    * **优雅退出**：正常结束时调用 ``wait_all()``；Ctrl+C 时同样调用 ``wait_all()``
      并支持再次按 Ctrl+C 强制跳过。
    """

    def __init__(self, dataset: LeRobotDataset) -> None:
        self._dataset = dataset
        self._executor: ThreadPoolExecutor = ThreadPoolExecutor(
            max_workers=1, thread_name_prefix="bg_video_enc"
        )
        self._futures: list[Future] = []
        self._ep0_done: bool = False  # 快速路径标志，ep0 确认编码完成后恒为 True

    def submit(self, episode_index: int) -> None:
        """提交编码任务，立即返回，不阻塞主线程。"""
        future = self._executor.submit(self._encode, episode_index)
        self._futures.append(future)

    def _encode(self, episode_index: int) -> None:
        try:
            logging.info(f"⏳ [后台编码] Episode {episode_index} 开始编码...")
            self._dataset.encode_episode_videos(episode_index)
            logging.info(f"✓  [后台编码] Episode {episode_index} 编码完成")
        except Exception:
            logging.exception(f"✗  [后台编码] Episode {episode_index} 编码失败")

    def ensure_ep0_done(self) -> None:
        """
        确保 episode 0 的编码已完成。

        必须在调用 ``dataset.save_episode_data_only()`` for episode > 0 之前调用，
        以避免 ``encode_episode_videos(0)`` 中的 ``write_info()`` 与
        主线程 ``meta.save_episode()`` 产生 ``info.json`` 写竞争。
        """
        if self._ep0_done:
            return
        if self._futures:
            try:
                self._futures[0].result()  # block until ep0 encoding done
            except Exception:
                pass  # error already logged in _encode
        self._ep0_done = True

    def wait_all(self) -> None:
        """
        等待所有后台编码任务完成。程序退出前必须调用。
        再次按 Ctrl+C 可强制跳过（部分视频将不完整）。
        """
        pending = sum(1 for f in self._futures if not f.done())
        if pending:
            logging.info(
                f"⏳ 等待 {pending} 个后台视频编码任务完成，请勿关闭程序…"
                "（再次按 Ctrl+C 可强制跳过）"
            )
        interrupted = False
        for future in self._futures:
            if interrupted:
                future.cancel()
                continue
            try:
                future.result()
            except KeyboardInterrupt:
                logging.warning("⚠  强制跳过剩余编码任务，部分视频可能不完整")
                self._executor.shutdown(wait=False, cancel_futures=True)
                interrupted = True
            except Exception:
                logging.exception("后台编码任务异常")
        if not interrupted:
            self._executor.shutdown(wait=False)
            if self._futures:
                logging.info("✓  所有后台视频编码任务已完成")

    def has_pending(self) -> bool:
        """返回是否有尚未完成的编码任务。"""
        return any(not f.done() for f in self._futures)

    def wait_latest(self) -> None:
        """
        等待最近提交的一个编码任务完成。

        在下一集 record_loop 启动之前调用，防止后台 SVT-AV1 编码器
        占用大量 CPU 导致相机读取线程饿死（async_read 200 ms 超时崩溃）。

        若上一集编码已完成则立即返回，不阻塞。
        """
        if not self._futures:
            return
        last = self._futures[-1]
        if last.done():
            return
        logging.info("⏳ 等待上一集视频编码完成，完成后自动开始录制…")
        try:
            last.result()
            logging.info("✓  编码完成，开始录制下一集")
        except Exception:
            pass  # error already logged in _encode

    def shutdown_cancel(self) -> None:
        """立即取消所有尚未开始的任务（强制退出时调用）。"""
        self._executor.shutdown(wait=False, cancel_futures=True)


def _stdin_has_enter() -> bool:
    """
    非阻塞地检测 stdin 中是否有 Enter（\\n）。
    使用 os.read 而非 readline，避免 Esc 转义序列（\\x1b）导致 readline 阻塞。
    """
    rlist, _, _ = select.select([sys.stdin], [], [], 0.1)
    if not rlist:
        return False
    data = os.read(sys.stdin.fileno(), 256)
    return b"\n" in data


def _wait_for_next_episode(events: dict, current_task: str, header: str) -> str | None:
    """
    每集结束后阻塞等待用户准备好再开始下一集。

    - 直接按 Enter   → 沿用当前任务描述，开始下一集
    - 按 Shift       → 预填当前任务到输入框，编辑后按 Enter 开始
    - 按 Esc         → 停止全部采集，返回 None

    Args:
        events:       来自 init_keyboard_listener() 的全局事件字典
        current_task: 当前任务描述
        header:       第一行提示标题（描述刚发生了什么）
    """
    from pynput import keyboard as kb
    import time

    shift_triggered = threading.Event()

    def _on_key(key):
        if key in (kb.Key.shift, kb.Key.shift_l, kb.Key.shift_r):
            shift_triggered.set()

    W = 62
    print(f"\n{'═' * W}")
    print(f"  {header}")
    print(f"{'─' * W}")
    print("  重置场景后，选择下一步操作：")
    print("    · 直接按 Enter   → 开始下一集（沿用当前任务）")
    print("    · 按 Shift       → 修改任务描述后按 Enter 开始")
    print("    · 按 Esc         → 停止全部采集")
    print(f"{'─' * W}")
    print(f"  当前任务：{current_task}")
    print(f"{'═' * W}")
    print("  > 等待按键…", flush=True)

    # ── 在打印提示之后再 flush stdin ──────────────────────────────────────
    # Page Up/Down 的转义序列（\x1b[5~、\x1b[6~）和其他残留字节在主线程
    # 处理 record_loop 退出期间可能已经进入 stdin 缓冲区。
    # 先 sleep 一小段让所有转义序列全部到达，再一次性 flush，
    # 确保等待 Enter 的循环只响应用户在提示出现之后主动按下的键。
    time.sleep(0.15)
    try:
        termios.tcflush(sys.stdin, termios.TCIFLUSH)
    except Exception:
        pass  # 非 tty 环境（如重定向）跳过

    listener = kb.Listener(on_press=_on_key)
    listener.start()

    try:
        while True:
            # ① 优先检查 Esc（stop_recording 由全局 listener 设置）
            if events["stop_recording"]:
                return None

            # ② Shift 触发：进入任务描述编辑模式
            if shift_triggered.is_set():
                listener.stop()
                shift_triggered.clear()

                print("  修改任务描述（当前内容已预填，可直接编辑）：")
                # 用 readline 预填当前任务，让用户看到并编辑
                readline.set_startup_hook(lambda: readline.insert_text(current_task))
                try:
                    new_text = input("  > ").strip()
                finally:
                    readline.set_startup_hook(None)
                    # 文本输入过程中按方向键会触发全局 listener → 置 exit_early/
                    # rerecord_episode，必须立即清除，否则下一轮 record_loop 会
                    # 在第一帧就因 exit_early=True 退出，看起来"没有遥操作"。
                    events["exit_early"] = False
                    events["rerecord_episode"] = False
                    # 同时再次 flush stdin（方向键转义序列可能残留）
                    try:
                        termios.tcflush(sys.stdin, termios.TCIFLUSH)
                    except Exception:
                        pass

                if new_text:
                    current_task = new_text
                print(f"\n  ✓ 任务已更新：{current_task}")
                print("  准备好后按 Enter 开始录制…\n")

                # 等待最终的 Enter
                while True:
                    if events["stop_recording"]:
                        return None
                    if _stdin_has_enter():
                        return current_task

            # ③ 检测普通 Enter 键
            if _stdin_has_enter():
                return current_task

    finally:
        if listener.is_alive():
            listener.stop()


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(t, (so100_leader.SO100Leader, so101_leader.SO101Leader, koch_leader.KochLeader))
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # if policy is given it needs cleaning up
    if policy is not None:
        policy.reset()

    timestamp = 0
    start_episode_t = time.perf_counter()
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        observation = robot.get_observation()

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, observation, prefix="observation")

        if policy is not None:
            action_values = predict_action(
                observation_frame,
                policy,
                get_safe_torch_device(policy.config.device),
                policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )
            action = {key: action_values[i].item() for i, key in enumerate(robot.action_features)}
        elif policy is None and isinstance(teleop, Teleoperator):
            action = teleop.get_action()
        elif policy is None and isinstance(teleop, list):
            # TODO(pepijn, steven): clean the record loop for use of multiple robots (possibly with pipeline)
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}

            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)

            action = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
        else:
            logging.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset.
        sent_action = robot.send_action(action)

        if dataset is not None:
            action_frame = build_dataset_frame(dataset.features, sent_action, prefix="action")
            frame = {**observation_frame, **action_frame}
            dataset.add_frame(frame, task=single_task)

        if display_data:
            log_rerun_data(observation, action)

        dt_s = time.perf_counter() - start_loop_t
        busy_wait(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        _init_rerun(session_name="recording")

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    action_features = hw_to_dataset_features(robot.action_features, "action", cfg.dataset.video)
    obs_features = hw_to_dataset_features(robot.observation_features, "observation", cfg.dataset.video)
    dataset_features = {**action_features, **obs_features}

    if cfg.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            )
        sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
    else:
        # Create empty dataset or load existing saved episodes
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

    # Load pretrained policy
    policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)

    robot.connect()
    if teleop is not None:
        teleop.connect()

    listener, events = init_keyboard_listener()

    with VideoEncodingManager(dataset):
        recorded_episodes = 0
        current_task = cfg.dataset.single_task
        bg_encoder = BackgroundVideoEncoder(dataset)

        try:
            while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                ep_display = f"Episode {recorded_episodes + 1} / {cfg.dataset.num_episodes}"
                log_say(f"Recording episode {recorded_episodes + 1}", cfg.play_sounds)

                W = 62
                print(f"\n{'═' * W}")
                print(f"  ▶ 开始录制 {ep_display}")
                print(f"  任务：{current_task}")
                print(f"{'─' * W}")
                print("  录制中按键：")
                print("    · Page Down    提前结束并保存")
                print("    · Page Up      丢弃本集，重新录制")
                print("    · Esc          停止全部采集")
                print(f"{'═' * W}\n")

                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop=teleop,
                    policy=policy,
                    dataset=dataset,
                    control_time_s=cfg.dataset.episode_time_s,
                    single_task=current_task,
                    display_data=cfg.display_data,
                )

                if events["rerecord_episode"]:
                    # ── 左方向键：丢弃当前 episode ──────────────────────────────
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    dataset.clear_episode_buffer()
                    logging.info(f"✗ {ep_display} 已丢弃，等待重新录制…")
                    wait_header = f"✗ {ep_display} 已丢弃 → 将重新录制"
                else:
                    # ── 时间到 / 右方向键：保存当前 episode ─────────────────────
                    # episode > 0 时确保 ep0 编码已完成，避免 info.json 写竞争
                    if recorded_episodes > 0:
                        bg_encoder.ensure_ep0_done()

                    logging.info(f"◎ {ep_display} 录制完毕，开始保存数据…")
                    episode_index = dataset.save_episode_data_only()
                    logging.info(
                        f"✓ {ep_display} 数据已落盘（parquet + 元数据），"
                        f"视频编码已提交后台线程（Episode {episode_index}）"
                    )
                    bg_encoder.submit(episode_index)
                    recorded_episodes += 1
                    wait_header = f"✓ {ep_display} 已保存（后台编码进行中）"

                # 最后一集已完成则退出，不再等待
                if recorded_episodes >= cfg.dataset.num_episodes or events["stop_recording"]:
                    break

                # ── 阻塞等待用户准备好，可选更新任务描述 ──────────────────────
                new_task = _wait_for_next_episode(events, current_task, header=wait_header)
                # 等待期间若误触方向键会污染 events；进入下一轮录制前必须清除，
                # 否则 record_loop 第一帧就因 exit_early=True 立即退出。
                events["exit_early"] = False
                events["rerecord_episode"] = False
                if new_task is None:
                    break
                current_task = new_task


        finally:
            # 无论正常结束还是异常/Ctrl+C，都等待所有后台编码完成
            # 再让 VideoEncodingManager.__exit__ 清理 PNG 目录
            bg_encoder.wait_all()

    log_say("Stop recording", cfg.play_sounds, blocking=True)

    robot.disconnect()
    if teleop is not None:
        teleop.disconnect()

    if not is_headless() and listener is not None:
        listener.stop()

    if cfg.dataset.push_to_hub:
        dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

    log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    record()


if __name__ == "__main__":
    main()
